### PR TITLE
Adding support for playsinline for iOS

### PR DESCRIPTION
**Pull request by codewithwaleed**
Adding support for playsinline for iOS

### CODE REVIEW

**Comment by third774** [comment]
Can you clarify what issue you're running into? The player already puts the `playsinline` attribute on the video element for iOS, and the iframe embed doesn't accept a `playsinline` search parameter.

**Comment by codewithwaleed** [comment]
> Can you clarify the issue you're running into and seeking to address? The player already puts the `playsinline` attribute on the video element for iOS, and the iframe embed doesn't accept a `playsinline` search parameter.

On iOS autoload is not working. I wanted to play it once the video loaded. Its working fine on windows and android devices but not on iOS.

**Comment by third774** [comment]
Would you mind sharing a reproduction of the issue? One thing to maybe check — are you setting `muted={true}`? iOS has a pretty strict policy against autoplay with audio enabled.

**Comment by codewithwaleed** [comment]
> Would you mind sharing a reproduction of the issue? One thing to maybe check — are you setting `muted={true}`? iOS has a pretty strict policy against autoplay with audio enabled.

Yes I know, I am setting it true.

**Comment by third774** [comment]
Closing this for now. Please open an issue with a reproduction of the issue and we'll be happy to take a look! 🙏🏻

**Pull request closed without merging**
